---
- name: change the hostname
  hostname:
    name="{{ inventory_hostname }}"
  when:
    ansible_fqdn != ansible_ssh_host

- name: update /etc/hosts from inventory
  lineinfile: dest=/etc/hosts regexp='.*{{item}}$' line='{{hostvars[item].ansible_default_ipv4.address}} {{item}}' state=present
  with_items: '{{ groups.rabbitmq }}'

- name: install nessesary package
  apt:
      name: apt-transport-https
      state: present
      update_cache: yes

- name: download esl-erlang package
  get_url:
    url: https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_22.3.1-1~debian~buster_amd64.deb
    dest: /opt/esl-erlang_22.3.1-1~debian~buster_amd64.deb
    mode: 0755

- name: install esl-erlang
  apt:
    deb: /opt/esl-erlang_22.3.1-1~debian~buster_amd64.deb

- name: download erlang solutions
  get_url:
    url: https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
    dest: /opt/erlang-solutions_2.0_all.deb
    mode: 0755

- name: install erlang repository
  apt:
    deb: /opt/erlang-solutions_2.0_all.deb

- name: add an Apt signing key
  apt_key:
    url: https://packages.erlang-solutions.com/debian/erlang_solutions.asc
    state: present

- name: fix unmet dependencies
  shell: apt-get -f install

- name: add rabbit repo
  shell: echo "deb https://dl.bintray.com/rabbitmq/debian buster main" | tee /etc/apt/sources.list.d/bintray.rabbitmq.list

- name: add trusted key
  shell: wget -O-  https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc | apt-key add -

- name: install rabbitmq
  apt:
    name: rabbitmq-server
    state: present
    update_cache: yes

- name: install rabbitmq
  apt:
    name: python-pip
    state: present

- name: install pip module for queues rabbitmq
  pip:
    name: requests

- name: rabbitmq default file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: rabbitmq-server.j2 , dest: /etc/default/rabbitmq-server }
    - { src: rabbitmq.config.j2, dest: /etc/rabbitmq/rabbitmq.config }
  notify:
    restart rabbitmq-server
